export const catsData = [
  { id: 1, breed: "Мейн-кун", popularity: 1, weight: 8, age: "12-15" },
  { id: 2, breed: "Британская короткошерстная", popularity: 2, weight: 5, age: "12-17" },
  { id: 3, breed: "Сфинкс", popularity: 3, weight: 4, age: "8-14" },
  { id: 4, breed: "Сиамская", popularity: 4, weight: 4, age: "15-20" },
  { id: 5, breed: "Персидская", popularity: 5, weight: 5, age: "12-17" },
  { id: 6, breed: "Русская голубая", popularity: 6, weight: 4, age: "15-20" },
  { id: 7, breed: "Бенгальская", popularity: 7, weight: 5, age: "12-16" },
  { id: 8, breed: "Норвежская лесная", popularity: 8, weight: 6, age: "14-16" },
  { id: 9, breed: "Шотландская вислоухая", popularity: 9, weight: 4, age: "11-14" },
  { id: 10, breed: "Абиссинская", popularity: 10, weight: 4, age: "9-15" },
  { id: 11, breed: "Рэгдолл", popularity: 11, weight: 7, age: "12-15" },
  { id: 12, breed: "Ориентальная", popularity: 12, weight: 5, age: "12-15" },
  { id: 13, breed: "Бурманская", popularity: 13, weight: 5, age: "10-16" },
  { id: 14, breed: "Турецкая ангора", popularity: 14, weight: 4, age: "12-18" },
  { id: 15, breed: "Сибирская", popularity: 15, weight: 6, age: "11-18" },
  { id: 16, breed: "Бомбейская", popularity: 16, weight: 4, age: "12-16" },
  { id: 17, breed: "Тонкинская", popularity: 17, weight: 4, age: "10-16" },
  { id: 18, breed: "Египетская мау", popularity: 18, weight: 4, age: "13-16" },
  { id: 19, breed: "Гавана браун", popularity: 19, weight: 4, age: "12-15" },
  { id: 20, breed: "Корниш-рекс", popularity: 20, weight: 3, age: "11-15" },
  { id: 21, breed: "Девон-рекс", popularity: 21, weight: 3, age: "9-15" },
  { id: 22, breed: "Японский бобтейл", popularity: 22, weight: 3, age: "9-15" },
  { id: 23, breed: "Американский керл", popularity: 23, weight: 4, age: "9-13" },
  { id: 24, breed: "Селкирк-рекс", popularity: 24, weight: 5, age: "10-15" },
  { id: 25, breed: "Лаперм", popularity: 25, weight: 4, age: "10-15" },
  { id: 26, breed: "Мэнкс", popularity: 26, weight: 4, age: "8-14" },
  { id: 27, breed: "Пиксибоб", popularity: 27, weight: 6, age: "13-15" },
  { id: 28, breed: "Саванна", popularity: 28, weight: 7, age: "12-20" },
  { id: 29, breed: "Чаузи", popularity: 29, weight: 7, age: "12-14" },
  { id: 30, breed: "Оцикет", popularity: 30, weight: 5, age: "10-15" },
  { id: 31, breed: "Сомалийская", popularity: 31, weight: 4, age: "12-16" },
  { id: 32, breed: "Турецкий ван", popularity: 32, weight: 6, age: "12-17" },
  { id: 33, breed: "Американская короткошерстная", popularity: 33, weight: 5, age: "15-20" },
  { id: 34, breed: "Экзотическая короткошерстная", popularity: 34, weight: 5, age: "12-15" },
  { id: 35, breed: "Бирманская", popularity: 35, weight: 5, age: "12-16" },
  { id: 36, breed: "Нибелунг", popularity: 36, weight: 4, age: "15-18" },
  { id: 37, breed: "Рагамаффин", popularity: 37, weight: 7, age: "12-16" },
  { id: 38, breed: "Сноу-шу", popularity: 38, weight: 5, age: "14-20" },
  { id: 39, breed: "Австралийский мист", popularity: 39, weight: 4, age: "12-16" },
  { id: 40, breed: "Кимрик", popularity: 40, weight: 4, age: "8-14" },
  { id: 41, breed: "Невская маскарадная", popularity: 41, weight: 6, age: "12-17" },
  { id: 42, breed: "Европейская короткошерстная", popularity: 42, weight: 5, age: "14-20" },
  { id: 43, breed: "Калифорнийская сияющая", popularity: 43, weight: 5, age: "9-16" },
  { id: 44, breed: "Бурмилла", popularity: 44, weight: 4, age: "10-15" },
  { id: 45, breed: "Гималайская", popularity: 45, weight: 5, age: "9-15" },
  { id: 46, breed: "Корат", popularity: 46, weight: 4, age: "10-15" },
  { id: 47, breed: "Манчкин", popularity: 47, weight: 3, age: "12-15" },
  { id: 48, breed: "Петерболд", popularity: 48, weight: 4, age: "12-15" },
  { id: 49, breed: "Тойгер", popularity: 49, weight: 5, age: "10-15" },
  { id: 50, breed: "Украинский левкой", popularity: 50, weight: 4, age: "12-15" }
];

export const sortFields = [
  { value: "", text: "Не выбрано" },
  { value: "id", text: "№" },
  { value: "breed", text: "Порода" },
  { value: "popularity", text: "Популярность" },
  { value: "weight", text: "Вес (кг)" },
  { value: "age", text: "Возраст (лет)" }
];

export const chartFields = [
  { value: "id", text: "№" },
  { value: "popularity", text: "Популярность" },
  { value: "weight", text: "Вес (кг)" }
];